### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by seblund** [Ecdar-SW5/Reveaal#9]
The goal is to be able to simulate **valid** runs (As described in Martijn's slides) of components (specifications) and of _conjunctions_, _parallel compositions_ and _quotients_ between them. This requires changing the GRPC/ProtoBuf
protocol in collaboration with the GUI team such that the GUI has enough information to choose a **valid** transition while the engine remains responsible for all logic.

**Comment by CasperStaahl** [comment]
estimated to 4 weeks
